site_name: TheBelvedereGlacier Handbook
site_url: https://labmgf-polimi.github.io/thebelvedereglacier-handbook

# Configuration
theme:
  name: material
  palette:
    #primary: blue grey
    #accent: cyan
    # Palette toggle for light mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Open Sans
  language: en
  features:
    - navigation.path
    - navigation.footer

# Customisation
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LabMGF
    - icon: fontawesome/brands/github
      link: https://github.com/labmgf-polimi
  consent:
    title: Cookie consent
    description: >-


      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

repo_url: https://github.com/labmgf-polimi/thebelvedereglacier-handbook

plugins:
  - search

# Page tree
nav:
  - Home: index.md
  - Website: website-intro.md
  - Exploring the glacier:
      - 3D Viewer: 3d-viewer.md
      - 2D Map explorer: 2d-map-explorer.md
      - Open Data: glacier-open-data.md
  - Learning resources: learning-resources.md
  - References: biblio.md


